/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SocialLinksProfileMainIndexImport } from './routes/social-links-profile-main/index'
import { Route as ReferencesIndexImport } from './routes/references/index'
import { Route as RecipePageMainIndexImport } from './routes/recipe-page-main/index'
import { Route as NorwayMountainsIndexImport } from './routes/norway-mountains/index'
import { Route as BlogPreviewCardMainIndexImport } from './routes/blog-preview-card-main/index'
import { Route as ArtYakaterinburgIndexImport } from './routes/art-yakaterinburg/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SocialLinksProfileMainIndexRoute =
  SocialLinksProfileMainIndexImport.update({
    id: '/social-links-profile-main/',
    path: '/social-links-profile-main/',
    getParentRoute: () => rootRoute,
  } as any)

const ReferencesIndexRoute = ReferencesIndexImport.update({
  id: '/references/',
  path: '/references/',
  getParentRoute: () => rootRoute,
} as any)

const RecipePageMainIndexRoute = RecipePageMainIndexImport.update({
  id: '/recipe-page-main/',
  path: '/recipe-page-main/',
  getParentRoute: () => rootRoute,
} as any)

const NorwayMountainsIndexRoute = NorwayMountainsIndexImport.update({
  id: '/norway-mountains/',
  path: '/norway-mountains/',
  getParentRoute: () => rootRoute,
} as any)

const BlogPreviewCardMainIndexRoute = BlogPreviewCardMainIndexImport.update({
  id: '/blog-preview-card-main/',
  path: '/blog-preview-card-main/',
  getParentRoute: () => rootRoute,
} as any)

const ArtYakaterinburgIndexRoute = ArtYakaterinburgIndexImport.update({
  id: '/art-yakaterinburg/',
  path: '/art-yakaterinburg/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/art-yakaterinburg/': {
      id: '/art-yakaterinburg/'
      path: '/art-yakaterinburg'
      fullPath: '/art-yakaterinburg'
      preLoaderRoute: typeof ArtYakaterinburgIndexImport
      parentRoute: typeof rootRoute
    }
    '/blog-preview-card-main/': {
      id: '/blog-preview-card-main/'
      path: '/blog-preview-card-main'
      fullPath: '/blog-preview-card-main'
      preLoaderRoute: typeof BlogPreviewCardMainIndexImport
      parentRoute: typeof rootRoute
    }
    '/norway-mountains/': {
      id: '/norway-mountains/'
      path: '/norway-mountains'
      fullPath: '/norway-mountains'
      preLoaderRoute: typeof NorwayMountainsIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipe-page-main/': {
      id: '/recipe-page-main/'
      path: '/recipe-page-main'
      fullPath: '/recipe-page-main'
      preLoaderRoute: typeof RecipePageMainIndexImport
      parentRoute: typeof rootRoute
    }
    '/references/': {
      id: '/references/'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesIndexImport
      parentRoute: typeof rootRoute
    }
    '/social-links-profile-main/': {
      id: '/social-links-profile-main/'
      path: '/social-links-profile-main'
      fullPath: '/social-links-profile-main'
      preLoaderRoute: typeof SocialLinksProfileMainIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/art-yakaterinburg': typeof ArtYakaterinburgIndexRoute
  '/blog-preview-card-main': typeof BlogPreviewCardMainIndexRoute
  '/norway-mountains': typeof NorwayMountainsIndexRoute
  '/recipe-page-main': typeof RecipePageMainIndexRoute
  '/references': typeof ReferencesIndexRoute
  '/social-links-profile-main': typeof SocialLinksProfileMainIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/art-yakaterinburg': typeof ArtYakaterinburgIndexRoute
  '/blog-preview-card-main': typeof BlogPreviewCardMainIndexRoute
  '/norway-mountains': typeof NorwayMountainsIndexRoute
  '/recipe-page-main': typeof RecipePageMainIndexRoute
  '/references': typeof ReferencesIndexRoute
  '/social-links-profile-main': typeof SocialLinksProfileMainIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/art-yakaterinburg/': typeof ArtYakaterinburgIndexRoute
  '/blog-preview-card-main/': typeof BlogPreviewCardMainIndexRoute
  '/norway-mountains/': typeof NorwayMountainsIndexRoute
  '/recipe-page-main/': typeof RecipePageMainIndexRoute
  '/references/': typeof ReferencesIndexRoute
  '/social-links-profile-main/': typeof SocialLinksProfileMainIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/art-yakaterinburg'
    | '/blog-preview-card-main'
    | '/norway-mountains'
    | '/recipe-page-main'
    | '/references'
    | '/social-links-profile-main'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/art-yakaterinburg'
    | '/blog-preview-card-main'
    | '/norway-mountains'
    | '/recipe-page-main'
    | '/references'
    | '/social-links-profile-main'
  id:
    | '__root__'
    | '/'
    | '/art-yakaterinburg/'
    | '/blog-preview-card-main/'
    | '/norway-mountains/'
    | '/recipe-page-main/'
    | '/references/'
    | '/social-links-profile-main/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtYakaterinburgIndexRoute: typeof ArtYakaterinburgIndexRoute
  BlogPreviewCardMainIndexRoute: typeof BlogPreviewCardMainIndexRoute
  NorwayMountainsIndexRoute: typeof NorwayMountainsIndexRoute
  RecipePageMainIndexRoute: typeof RecipePageMainIndexRoute
  ReferencesIndexRoute: typeof ReferencesIndexRoute
  SocialLinksProfileMainIndexRoute: typeof SocialLinksProfileMainIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtYakaterinburgIndexRoute: ArtYakaterinburgIndexRoute,
  BlogPreviewCardMainIndexRoute: BlogPreviewCardMainIndexRoute,
  NorwayMountainsIndexRoute: NorwayMountainsIndexRoute,
  RecipePageMainIndexRoute: RecipePageMainIndexRoute,
  ReferencesIndexRoute: ReferencesIndexRoute,
  SocialLinksProfileMainIndexRoute: SocialLinksProfileMainIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/art-yakaterinburg/",
        "/blog-preview-card-main/",
        "/norway-mountains/",
        "/recipe-page-main/",
        "/references/",
        "/social-links-profile-main/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/art-yakaterinburg/": {
      "filePath": "art-yakaterinburg/index.jsx"
    },
    "/blog-preview-card-main/": {
      "filePath": "blog-preview-card-main/index.jsx"
    },
    "/norway-mountains/": {
      "filePath": "norway-mountains/index.jsx"
    },
    "/recipe-page-main/": {
      "filePath": "recipe-page-main/index.jsx"
    },
    "/references/": {
      "filePath": "references/index.jsx"
    },
    "/social-links-profile-main/": {
      "filePath": "social-links-profile-main/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
